# For more information: https://laravel.com/docs/sail
version: '3.3'
services:
    genius-coding:
        build:
            context: .
            dockerfile: Dockerfile-dev
        image: genius-coding
        restart: unless-stopped
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            VIRTUAL_HOST: genius-coding.local
            VIRTUAL_PORT: 80
            XDEBUG_TRIGGER: 1
        volumes:
            - '.:/var/www/html'
            - '/var/www/html/vendor'
        networks:
            - genius-coding-network
        depends_on:
            - mysql-db

    mysql-db:
        image: mysql:8.0.25
        container_name: mysql-db
        restart: unless-stopped
        tty: true
        ports:
            - "10501:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql-files
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: "mysqladmin ping -h localhost"
            interval: 1s
            timeout: 1s
            retries: 60
        networks:
            - genius-coding-network

volumes:
    dbdata:
        driver: local

networks:
    genius-coding-network:
        external: true


